apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-envoy-config
  namespace: istio-system
data:
  config.yaml: |
    services:
      - name: opa
        url: http://opa.istio-system.svc.cluster.local:8181
    rules:
      - match: destination.namespace == "backend"
        destination: opa.istio-system
